#!/usr/bin/python


import time
import datetime
import psutil
import netifaces
import subprocess


def network_status():
    try:
        return ('wlp3s0 : ' + netifaces.ifaddresses('wlp3s0')[2][0]['addr'])
    except:
        return ('wlp3s0 : Not connected')



def battery_status():
    battery = psutil.sensors_battery()
    plugged = battery.power_plugged
    percent = str('%.2f' % (battery.percent))
    plugged = "+" if plugged else "-"
    return (plugged+percent+'%')

def date_status():
    return datetime.datetime.now().ctime()




while True:
    try:
        subprocess.run(['xsetroot', '-name', network_status() + ' | ' +battery_status()+ ' | ' + date_status()])
        time.sleep(10)
    except:
        time.sleep(1)
        pass

